// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NArchitectureCodeGenerator.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidNArchitectureCodeGeneratorPackageString = "d20044c4-8101-4adf-be40-b3a57c247c96";
        public static Guid guidNArchitectureCodeGeneratorPackage = new Guid(guidNArchitectureCodeGeneratorPackageString);

        public const string guidNArchitectureCodeGeneratorPackageCmdSetString = "d7dda713-9385-4a96-94e6-4241e00ad46a";
        public static Guid guidNArchitectureCodeGeneratorPackageCmdSet = new Guid(guidNArchitectureCodeGeneratorPackageCmdSetString);

        public const string guidImagesString = "47521464-f92c-4b34-a72c-b3d60f03493e";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CodeGeneratorMenuGroup = 0x1020;
        public const int CodeGeneratorCommandId = 0x0100;
        public const int Img1 = 0x0001;
    }
}