using NArchitectureCodeGenerator.CodeGenerator.ServiceRegistrationOperations.Entities;
using NArchitectureCodeGenerator.CodeGenerator.ServiceRegistrationOperations.Registrators.Abstract;
using NArchitectureCodeGenerator.Extensions;
using NArchitectureCodeGenerator.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NArchitectureCodeGenerator.CodeGenerator.ServiceRegistrationOperations.Registrators.Concrete
{
    public class ApplicationServiceRegistrator : BaseRegistrator
    {
        protected override void ControlUsingStatements(ref List<string> lines, string entityName)
        {
            var usingStatement = $"using {ProjectHelper.ApplicationProjectName}.Features.{entityName.Pluralize()}.Rules;";

            if (!lines.Any(line => line.Contains(usingStatement)))
                lines.Insert(0, usingStatement);

        }

        protected override string GetFilePath()
        {
            return PathHelper.CombinePaths(PathHelper.RootPath, ProjectHelper.ApplicationProjectName, "ApplicationServiceRegistration.cs");
        }

        protected override List<LineNumberDecider> GetLineNumberDeciderList()
        {

            return new List<LineNumberDecider>
            {
                new LineNumberDecider(".*\\/\\/\\*\\*\\*Business rules here - autogenerated\\*\\*\\*.*$", 1),
                new LineNumberDecider(".*AddScoped<.*>.*", 1),
                new LineNumberDecider(".*public static IServiceCollection AddApplicationServices.*", 0, true),
                new LineNumberDecider(".*return.*", -1)
            };

        }

        protected override string GetLineContentToAdd(string entityName)
        {
            return $"\t\t\tservices.AddScoped<{entityName}BusinessRules>();";
        }
    }
}
