using NArchitectureCodeGenerator.Helpers.FileAppenderHelper.Entities;
using NArchitectureCodeGenerator.Helpers.FileAppenderHelper.Appenders.Abstract;
using NArchitectureCodeGenerator.Extensions;
using NArchitectureCodeGenerator.Helpers;
using NArchitectureCodeGenerator.Helpers.FileHelper.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NArchitectureCodeGenerator.Helpers.FileAppenderHelper.Appenders.Concrete
{
    public class DbContextAppender : BaseAppenderForCodeGenerator
    {
        public DbContextAppender(IFileService fileService) : base(fileService)
        {
        }

        protected override void ControlUsingStatements(ref List<string> lines)
        {
            var usingStatement = $"using {ProjectHelper.DomainProjectName}.Entities;";

            if (!lines.Any(line => line.Contains(usingStatement)))
                lines.Insert(0, usingStatement);
        }

        protected override string GetFilePath()
        {
            return _fileService.CombinePaths(ProjectHelper.RootPath, ProjectHelper.PersistenceProjectName, "Contexts", "BaseDbContext.cs");
        }

        protected override string GetLineContentToAdd()
        {
            return $"\t\tpublic DbSet<{_entityInfo.Name}> {_entityInfo.Name.Pluralize()} {{ get; set; }}";
        }

        protected override List<LineNumberDecider> GetLineNumberDeciderList()
        {
            return new List<LineNumberDecider>
            {
                new LineNumberDecider(".*public DbSet<.*>.*{.*get;.*set;.*}.*", 1),
                new LineNumberDecider(".*\\/\\/\\*\\*\\*DbSet here - autogenerated\\*\\*\\*.*$", 1),
                new LineNumberDecider(".*public class BaseDbContext : DbContext.*", 0, true)
            };

        }
    }
}
